import { cacheNames, clientsClaim, type RouteHandlerCallbackOptions } from 'workbox-core'
import { registerRoute, setCatchHandler } from 'workbox-routing'
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { ExpirationPlugin } from 'workbox-expiration'
import type { ManifestEntry } from 'workbox-build'

declare type ServiceWorkerGlobalScope = any
declare type ExtendableEvent = any
declare let self: ServiceWorkerGlobalScope

// Keep the console clean in production
self.__WB_DISABLE_DEV_LOGS = true

const DEFAULT_RECIPE_BASE = 'https://raw.githubusercontent.com/luxor37/mycookbook_lib/main'
const recipeBase = (
  // Nuxt exposes public env vars on import.meta.env
  (import.meta as any)?.env?.NUXT_PUBLIC_RECIPE_BASE_URL ||
  DEFAULT_RECIPE_BASE
).replace(/\/$/, '')

const APP_SHELL_FALLBACK = '/index.html'
const recipeJsonCache = 'recipe-json-v1'
const recipeImageCache = 'recipe-images-v1'
const pageCache = 'pages-v1'

const typeToDir: Record<string, string> = {
  REPAS: 'repas',
  ENTREES: 'entrees',
  DESSERTS: 'desserts',
  BOISSONS: 'boissons',
  CLEANING_PRODUCTS: "produits_nettoyants",
  AUTRES: 'autres',
  ALL: 'index'
}

// 1) Precache static assets generated by Vite PWA
precacheAndRoute(self.__WB_MANIFEST as Array<ManifestEntry>)
cleanupOutdatedCaches()

// 2) Cache navigations (HTML) with a custom handler:
// - try network and cache the response
// - if offline, fall back to cached navigation or the app shell
registerRoute(
  ({ request }) => request.mode === 'navigate',
  async ({ event }) => {
    const cache = await caches.open(pageCache)
    try {
      const response = await fetch(event.request)
      if (response && response.ok) await cache.put(event.request, response.clone())
      return response
    } catch (err) {
      const cached = await cache.match(event.request)
      return (
        cached ||
        (await caches.match(APP_SHELL_FALLBACK)) ||
        (await caches.match('/')) ||
        Response.error()
      )
    }
  }
)

// 3) Runtime caching for recipe JSON (index + each recipe)
registerRoute(
  ({ url, request }) =>
    request.method === 'GET' &&
    url.href.startsWith(`${recipeBase}/recipes/`) &&
    url.pathname.endsWith('index.json'),
  new NetworkFirst({
    cacheName: recipeJsonCache,
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 256 })
    ]
  })
)

// 4) Runtime caching for recipe images
registerRoute(
  ({ url, request }) =>
    request.destination === 'image' &&
    request.method === 'GET' &&
    url.href.startsWith(`${recipeBase}/recipes/`),
  new CacheFirst({
    cacheName: recipeImageCache,
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 256,
        maxAgeSeconds: 60 * 60 * 24 * 365 // 1 year
      })
    ]
  })
)

// 5) Runtime caching for styles/scripts/fonts not in the precache
registerRoute(
  ({ request }) =>
    ['style', 'script', 'font'].includes(request.destination),
  new StaleWhileRevalidate({
    cacheName: cacheNames.runtime,
    plugins: [new CacheableResponsePlugin({ statuses: [0, 200] })]
  })
)

// 6) Warm the recipe library so every recipe is available offline after first activation
const warmRecipeLibrary = async () => {
  try {
    const pageCacheHandle = await caches.open(pageCache)
    // cache the root document so the shell is available offline after first activation
    try {
      const pageResp = await fetch('/')
      if (pageResp.ok) {
        await pageCacheHandle.put('/', pageResp.clone())
        await pageCacheHandle.put(APP_SHELL_FALLBACK, pageResp.clone())
      }
    } catch (err) {
      console.warn('Unable to warm root page cache', err)
    }

    const jsonCache = await caches.open(recipeJsonCache)
    const imageCache = await caches.open(recipeImageCache)
    const indexUrl = `${recipeBase}/recipes/index.json`
    const indexResponse = await fetch(indexUrl)

    if (!indexResponse.ok) return
    await jsonCache.put(indexUrl, indexResponse.clone())

    const payload = await indexResponse.clone().json()
    const entries: Array<{ id: string; type: string }> = payload.recipes ?? []

    const targets: Array<{ url: string; cache: Cache }> = []
    for (const entry of entries) {
      const dir = typeToDir[entry.type] ?? 'autres'
      targets.push({ url: `${recipeBase}/recipes/${dir}/${entry.id}/index.json`, cache: jsonCache })
      targets.push({ url: `${recipeBase}/recipes/${dir}/${entry.id}/image.jpg`, cache: imageCache })
    }

    await Promise.allSettled(
      targets.map(async ({ url, cache }) => {
        const response = await fetch(url)
        if (response.ok) await cache.put(url, response)
      })
    )
  } catch (error) {
    console.error('Warm recipe cache failed', error)
  }
}

self.addEventListener('install', (event: ExtendableEvent) => {
  event.waitUntil(self.skipWaiting())
})

self.addEventListener('activate', (event: ExtendableEvent) => {
  event.waitUntil(Promise.all([clientsClaim(), warmRecipeLibrary()]))
})

// 7) Graceful offline fallback for documents
setCatchHandler(async ({ event, request }: RouteHandlerCallbackOptions) => {
  const destination = request?.destination || (event as FetchEvent)?.request?.destination
  if (destination === 'document') {
    const navRequest = request || (event as FetchEvent)?.request
    const cached =
      (navRequest && await caches.match(navRequest)) ||
      await caches.match(APP_SHELL_FALLBACK) ||
      await caches.match('/')
    if (cached) return cached
    return new Response(
      `<!doctype html><html><head><meta charset="utf-8"><title>Offline</title></head><body><h1>Vous êtes hors ligne</h1><p>Réessayez lorsque la connexion sera rétablie.</p></body></html>`,
      { headers: { 'Content-Type': 'text/html; charset=utf-8' } }
    )
  }
  return Response.error()
})
